-- Plugin Setup
require("plugins.colorscheme")
require("plugins.tree")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.lualine")
require("plugins.blink")
require("plugins.fzf")
require("plugins.which-key")
require("plugins.oil")
require("plugins.colorful-menu")
require("plugins.mini_setup")
require("plugins.precognition")
